category=Languages
description=OpenAPI language support for SonarQube. Enables SonarQube to analyze OpenAPI specifications. Serves as the foundation for OpenAPI analysis on SonarQube.
homepageUrl=https://github.com/apiaddicts/sonar-openapi
archivedVersions=
publicVersions=1.1.1

defaults.mavenGroupId=org.apiaddicts.apitools.dosonarapi
defaults.mavenArtifactId=sonar-openapi-plugin

1.1.1.description=Provides OpenAPI support, including file scanning, parsing, and analysis of YAML and JSON specifications.
1.1.1.sqs=[10.8,LATEST]
1.1.1.sqcb=[24.12,LATEST]
1.1.1.date=2024-09-05
1.1.1.changelogUrl=https://github.com/apiaddicts/sonar-openapi/releases/tag/v1.1.1
1.1.1.downloadUrl=https://repo1.maven.org/maven2/org/apiaddicts/apitools/dosonarapi/sonar-openapi-plugin/1.1.1/sonar-openapi-plugin-1.1.1.jar
