category=External Analyzers
description=Custom SonarQube rules to analyze and improve the quality, security, and consistency of OpenAPI.
homepageUrl=https://github.com/apiaddicts/sonaropenapi-rules
archivedVersions=
publicVersions=1.3.3

defaults.mavenGroupId=org.apiaddicts.apitools.dosonarapi
defaults.mavenArtifactId=sonaropenapi-rules-community

1.3.2.description=Analyze OpenAPI specifications v1.3.3
1.3.2.sqs=[10.8,LATEST]
1.3.2.sqcb=[24.12,LATEST]
1.3.2.date=2026-03-20
1.3.2.changelogUrl=https://github.com/apiaddicts/sonaropenapi-rules/releases/tag/1.3.3
1.3.2.downloadUrl=https://repo1.maven.org/maven2/org/apiaddicts/apitools/dosonarapi/sonaropenapi-rules-community/1.3.3/sonaropenapi-rules-community-1.3.3.jar