category=Visualization/Reporting
description=CycloneDX Sunshine SBOM Visualization for SonarQube projects
homepageUrl=https://github.com/mathiasconradt/sonarqube-cdx-sunshine-plugin
archivedVersions=
publicVersions=0.2.0

defaults.mavenGroupId=io.github.mathiasconradt
defaults.mavenArtifactId=sonarqube-cdx-sunshine-plugin

0.2.0.description=Update to correct plugin key (sbomviz -> cdxsunshine)
0.2.0.sqs=[2026.1,LATEST]
0.2.0.sqcb=
0.2.0.date=2026-06-26
0.2.0.changelogUrl=https://github.com/mathiasconradt/sonarqube-cdx-sunshine-plugin/releases/tag/v0.2.0
0.2.0.downloadUrl=https://github.com/mathiasconradt/sonarqube-cdx-sunshine-plugin/releases/download/v0.1.9/sonarqube-cdx-sunshine-plugin-0.2.0.jar
