category=Coverage
description=The Diffblue SonarQube Plugin calculates and visualises the coverage provided by Diffblue Cover's AI-generated unit tests inside SonarQube.
homepageUrl=https://github.com/diffblue/diffblue-sonar-plugin
archivedVersions=
publicVersions=1.0.0
defaults.mavenGroupId=com.diffblue
defaults.mavenArtifactId=diffblue-sonar-plugin

1.0.0.description=Initial release of the Diffblue SonarQube Plugin.
1.0.0.sqs=[9.9,2026.3.1]
1.0.0.sqcb=[25.1,26.7]
1.0.0.date=2026-02-27
1.0.0.changelogUrl=https://github.com/diffblue/diffblue-sonar-plugin/commits/v1.0.0
1.0.0.downloadUrl=https://github.com/diffblue/diffblue-sonar-plugin/releases/download/v1.0.0/diffblue-sonar-plugin-1.0.0.jar
