category=Scanners
name=SonarScanner for Cargo
license=GNU LGPL 3
organization=SonarSource
organizationUrl=https://www.sonarsource.com
homepageUrl=https://github.com/SonarSource/sonar-scanner-cargo
issueTrackerUrl=https://sonarsource.atlassian.net/jira/software/c/projects/SCANCARGO/issues
sourcesUrl=https://github.com/SonarSource/sonar-scanner-cargo
archivedVersions=
publicVersions=1.0.0

1.0.0.description=First generally available release. Runs an analysis with cargo sonar-scanner, configured from the [package.metadata.sonar] table in Cargo.toml.
1.0.0.date=2026-09-11
1.0.0.changelogUrl=https://github.com/SonarSource/sonar-scanner-cargo/releases/tag/1.0.0-105
1.0.0.downloadUrl=https://crates.io/crates/cargo-sonar-scanner/1.0.0
